// @ts-check
import { defineConfig } from "astro/config";
import preact from "@astrojs/preact";
import tailwindcss from "@tailwindcss/vite";

// Site URL drives canonical tags, sitemap, and OG absolute URLs.
const SITE = "https://calcyourfinance.com";

// https://astro.build/config
export default defineConfig({
  site: SITE,
  trailingSlash: "never",
  // Sitemap is generated by src/pages/sitemap.xml.ts as a single /sitemap.xml.
  integrations: [preact()],
  build: {
    // Clean URLs: /stripe-fee-calculator (not /stripe-fee-calculator/index.html)
    format: "file",
    inlineStylesheets: "auto",
  },
  vite: {
    plugins: [tailwindcss()],
  },
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },
});
